
networks:
  net1:



volumes:
    pgdata:
        driver: local


services:

  nginx:
    restart: always
    image: nginx:latest
    expose:
      - 8080
    ports:
      - 5000:8080
    depends_on:
      - web
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d


  web:
    restart: always
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    command: gunicorn -c gunicorn.py stocks_products.wsgi
    volumes:
      - ./project_django:/app/
    expose:
      - 8000
    ports:
      - 8000:8000


  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: aio
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: qwe

    ports:
      - 5433:5432
    networks:
      net1:
        aliases:
          - database